---
name: 'review-app'

# yamllint disable-line rule:truthy
on: pull_request

env:
  APP_NAME: review-${{ github.event.pull_request.number }}
  BASE_GIT_REMOTE_URL: ssh://dokku@${{ secrets.SERVER_IP }}:22/price-tracker-client
  REVIEW_GIT_REMOTE_URL: ssh://dokku@${{ secrets.SERVER_IP }}:22/review-${{ github.event.pull_request.number }}

jobs:
  create_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is opened
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push the review app
        uses: dokku/github-action@master
        with:
          # create a review app
          command: review-apps:create
          git_remote_url: ${{ env.BASE_GIT_REMOTE_URL }}
          review_app_name: ${{ env.APP_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Comment the review app URL in the PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "Review app created: [${{ env.APP_NAME }}](https://${{ env.APP_NAME }}.daam.deals)"


  deploy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is not opened or closed
    if: github.event_name == 'pull_request' && github.event.action != 'opened' && github.event.action != 'closed'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_push_flags: "--force"
          git_remote_url: ${{ env.REVIEW_GIT_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Destroy the review app
        uses: dokku/github-action@master
        with:
          # destroy a review app
          command: review-apps:destroy
          git_remote_url: ${{ env.REVIEW_GIT_REMOTE_URL }}
          # specify a name for the review app
          review_app_name: ${{ env.APP_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
